### ISSUE TITLE
Node 节点多网卡的情况　，calico 网络有问题

### ISSUE THREAD

**Issue by EamonZhang** [gjmzj/kubeasz#56]
不能指定网络根据网卡名指定选取的是哪个网关

**Comment by gjmzj** [comment]
多网卡可以解决的，已在calico-node启动参数指定使用的网卡IP，详见`roles/calico/templates/calico-node.service.j2`
如果出现问题可以在每个节点使用
`calicoctl node status`命令查看bgp邻居的地址是否正确，如果有问题可以更新最新项目代码，然后使用`ansible-playbook 05.calico.yml`重设calico网络

**Comment by evenye** [comment]
请问怎么指定网卡IP呢?  不太明白用什么参数才对? 

ExecStart={{ bin_dir }}/docker run --net=host --privileged --name=calico-node \
  -e ETCD_ENDPOINTS={{ ETCD_ENDPOINTS }} \
  -e ETCD_CA_CERT_FILE=/etc/calico/ssl/ca.pem \
  -e ETCD_CERT_FILE=/etc/calico/ssl/calico.pem \
  -e ETCD_KEY_FILE=/etc/calico/ssl/calico-key.pem \
  -e CALICO_LIBNETWORK_ENABLED=true \
  -e CALICO_NETWORKING_BACKEND=bird \
  -e CALICO_DISABLE_FILE_LOGGING=true \
  -e CALICO_IPV4POOL_CIDR={{ CLUSTER_CIDR }} \
  -e CALICO_IPV4POOL_IPIP=off \
  -e FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT \
  -e FELIX_IPV6SUPPORT=false \
  -e FELIX_LOGSEVERITYSCREEN=info \
  -e FELIX_IPINIPMTU=1440 \
  -e FELIX_HEALTHENABLED=true \
  -e IP= \
  -v /etc/calico/ssl:/etc/calico/ssl \
  -v /var/run/calico:/var/run/calico \
  -v /lib/modules:/lib/modules \
  -v /run/docker/plugins:/run/docker/plugins \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/log/calico:/var/log/calico \
  calico/node:v2.6.2
ExecStop={{ bin_dir }}/docker rm -f calico-node
Restart=always
RestartSec=10

**Comment by gjmzj** [comment]
sorry，可能我没说清楚，怎么改在项目`roles/calico/templates/calico-node.service.j2`文件里面已经改好了，文档可能没有及时更新

**Comment by 88265920** [comment]
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.10.52.120 | node-to-node mesh | start | 05:15:12 | Connect     |
| 192.168.5.7  | node-to-node mesh | up    | 05:15:16 | Established |
| 192.168.5.8  | node-to-node mesh | up    | 05:15:16 | Established |
| 192.168.5.9  | node-to-node mesh | up    | 05:15:16 | Established |
| 192.168.5.2  | node-to-node mesh | up    | 05:15:17 | Established |
| 192.168.5.5  | node-to-node mesh | up    | 05:15:17 | Established |
| 192.168.5.6  | node-to-node mesh | up    | 05:15:17 | Established |
+--------------+-------------------+-------+----------+-------------+

不知道我是不是也遇到了这个问题？

eth0      Link encap:Ethernet  HWaddr 00:50:56:b1:65:6f  
          inet addr:10.10.5.4  Bcast:10.10.255.255  Mask:255.255.0.0
          inet6 addr: fe80::250:56ff:feb1:656f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3462321 errors:0 dropped:18294 overruns:0 frame:0
          TX packets:2446825 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:694610280 (694.6 MB)  TX bytes:1280402371 (1.2 GB)

eth1      Link encap:Ethernet  HWaddr 00:50:56:b1:42:b1  
          inet addr:192.168.5.4  Bcast:192.168.255.255  Mask:255.255.0.0
          inet6 addr: fe80::250:56ff:feb1:42b1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:118762 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7935 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:14737422 (14.7 MB)  TX bytes:577297 (577.2 KB)

----------------------------------------------------------------------------------------------------

eth0      Link encap:Ethernet  HWaddr 10:7b:44:17:e7:c3  
          inet addr:10.10.52.120  Bcast:10.10.255.255  Mask:255.255.0.0
          inet6 addr: fe80::ee5c:407a:3d4c:6fb4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2088804 errors:0 dropped:16583 overruns:0 frame:0
          TX packets:1215870 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:742865935 (742.8 MB)  TX bytes:908541363 (908.5 MB)
          Interrupt:16 Memory:f7100000-f7120000

120就一个网卡
